<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="aspire1115" name="com.temenos.testscripts.StandingOrd" tests="1" failures="1" timestamp="15 Nov 2017 07:32:43 GMT" time="66.004" errors="0">
  <testcase name="TC_TCIB_StandinOrder_003" time="66.004" classname="com.temenos.testscripts.StandingOrd">
    <failure type="java.lang.AssertionError" message="Test Failed. Check the steps above in red color.">
      <![CDATA[java.lang.AssertionError: Test Failed. Check the steps above in red color.
	at org.testng.Assert.fail(Assert.java:94)
	at com.temenos.support.Log.fail(Log.java:447)
	at com.temenos.support.Log.testCaseResult(Log.java:216)
	at com.temenos.testscripts.StandingOrd.TC_TCIB_StandinOrder_003(StandingOrd.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- TC_TCIB_StandinOrder_003 -->
</testsuite> <!-- com.temenos.testscripts.StandingOrd -->
